# Permalinks
permalink:        pretty

# Setup
title:            'Right Brain Dominant'
tagline:          'Creative'
description:      'A blog about artistic and creative topics.'
markdown:         kramdown
url:              https://rightbraindominant.com
baseurl:          /

author:
  name:           'Prateek'
  url:            prateek.app

paginate:         1

# Custom vars
version:          1.0

github:
  repo:           https://github.com/random-cup/right-brain
